apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: 
    requests: 
      storage: 5Gi 
  selector:
    matchLabels:
        name: postgres-volume
  storageClassName: microk8s-hostpath
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    name: postgres-volume
spec:
  capacity:
    storage: 10Gi
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: postgres-volume
    fsType: ext4
    readOnly: true
