CREATE TABLE IF NOT EXISTS ACCESS
(
    ID VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    SHORTCODE VARCHAR(10) DEFAULT '',
    -- CID VARCHAR(10) DEFAULT '',
    CANPRINT VARCHAR(10) DEFAULT 'FALSE',
    CANLASERCUT VARCHAR(10) DEFAULT 'FALSE',
    VALID VARCHAR(10) DEFAULT 'FALSE',
    PRIORITY INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SENT
(
    SHORTCODE VARCHAR(10) DEFAULT '',
    TIME_ADDED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PRINT_METRICS
(
    SHORTCODE VARCHAR(10) DEFAULT '',
    TIME_STARTED TIMESTAMP DEFAULT NOW(),
    PRINT_DURATION INTEGER DEFAULT 0,
    PRINT_WEIGHT INTEGER DEFAULT 0,
    PRINTER_NAME VARCHAR(40) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS INDUCTION_QUIZ
(
    QUESTION TEXT NOT NULL,
    CORRECT_OPTIONS TEXT NOT NULL,
    INCORRECT_OPTIONS TEXT,
    NUM_ANSWERS INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS INDUCTION
(
    SHORTCODE VARCHAR(10) NOT NULL UNIQUE PRIMARY KEY,
    CANPRINT BOOLEAN DEFAULT '0',
    CANLASERCUT BOOLEAN DEFAULT '0',
    VALID BOOLEAN DEFAULT '0',
    PRIORITY INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SHORTCODE_CARD_MAPPING
(
    ID VARCHAR(20) NOT NULL,
    SHORTCODE VARCHAR(10) NOT NULL,
    PRIMARY KEY(ID, SHORTCODE)
);

INSERT INTO public.induction
SELECT DISTINCT shortcode, canprint='TRUE' print, canlasercut='TRUE' laser, valid='TRUE' FROM public.access

INSERT INTO public.shortcode_card_mapping 
SELECT id, shortcode valid FROM public.access 
WHERE id IS NOT NULL AND SHORTCODE IS NOT NULL;

