CREATE TABLE IF NOT EXISTS ACCESS
(
    ID VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
    SHORTCODE VARCHAR(10) DEFAULT '',
    -- CID VARCHAR(10) DEFAULT '',
    CANPRINT VARCHAR(10) DEFAULT 'FALSE',
    CANLASERCUT VARCHAR(10) DEFAULT 'FALSE',
    VALID VARCHAR(10) DEFAULT 'FALSE',
    PRIORITY INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SENT
(
    SHORTCODE VARCHAR(10) DEFAULT '',
    TIME_ADDED TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PRINT_METRICS
(
    SHORTCODE VARCHAR(10) DEFAULT '',
    TIME_STARTED TIMESTAMP DEFAULT NOW(),
    PRINT_DURATION INTEGER DEFAULT 0,
    PRINT_WEIGHT INTEGER DEFAULT 0,
    PRINTER_NAME VARCHAR(40) DEFAULT ''
);

CREATE TABLE IF NOT EXISTS INDUCTION_QUIZ
(
    QUESTION TEXT NOT NULL,
    CORRECT_OPTIONS TEXT NOT NULL,
    INCORRECT_OPTIONS TEXT,
    NUM_ANSWERS INTEGER NOT NULL
);
