CREATE SCHEMA IF NOT EXISTS occupancy;

CREATE TABLE IF NOT EXISTS occupancy.history
(
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shortcode TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT false
);
