CREATE TABLE IF NOT EXISTS ACCESS
(
	ID VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY,
	SHORTCODE VARCHAR(10) DEFAULT '',
	-- CID VARCHAR(10) DEFAULT '',
	CANPRINT VARCHAR(10) DEFAULT 'FALSE',
	CANLASERCUT VARCHAR(10) DEFAULT 'FALSE',
	VALID VARCHAR(10) DEFAULT 'FALSE',
	PRIORITY INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS SENT
(
	SHORTCODE VARCHAR(10) DEFAULT '',
	TIME_ADDED DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PRINT_METRICS
(
	SHORTCODE VARCHAR(10) DEFAULT '',
	TIME_STARTED DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRINT_DURATION INTEGER DEFAULT 0,
	PRINT_WEIGHT INTEGER DEFAULT 0,
	PRINTER_NAME VARCHAR(40) DEFAULT ""
);
