name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        # Provide the password for postgres
        image: postgres
        env:
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: psql -U $POSTGRES_USERNAME -d $POSTGRES_DATABASE -a -f src/discord_database.sql
    - run: psql -U $POSTGRES_USERNAME -d $POSTGRES_DATABASE -a -f src/lab_database.sql
