name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: echo "🎉 This job uses runner scale set runners!"
    - run: cat src/discord_database.sql
    - run: psql -U ${{ secrets.POSTGRES_USERNAME }} -d ${{ secrets.POSTGRES_DATABASE }} -a -f src/discord_database.sql
    - run: psql -U ${{ secrets.POSTGRES_USERNAME }} -d ${{ secrets.POSTGRES_DATABASE }} -a -f src/lab_database.sql
